theme: jekyll-theme-minimal


title: Welcome!
email: tara.alpert@yale.edu
logo: /assets/headshot4.jpg
description: 
  Postdoctoral fellow in the Grubaugh lab
  Epidemiology of Microbial Diseases
  Yale University School of Public Health  

# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]
github_username:  tdalpert

