theme: jekyll-theme-minimal


title: Welcome!
email: tara.alpert@yale.edu
logo: /assets/headshot3.jpg
description: 
  PhD candidate  \n
  Supervised by Dr. Karla Neugebauer  \n
  Molecular Biophysics & Biochemistry  \n
  Yale University  

# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]
github_username:  tdalpert

